# Generated by Django 6.0.3 on 2026-03-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('experience', models.CharField(blank=True, max_length=300)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='author_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
