# Generated by Django 6.0.3 on 2026-03-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BScIT', 'B.Sc IT'), ('BScCS', 'B.Sc CS')], max_length=20)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pyqs/')),
            ],
        ),
    ]
