# Generated by Django 6.0.3 on 2026-03-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyq',
            name='course',
            field=models.CharField(choices=[('BScIT', 'Bachelor of Science in Information Technology'), ('BScCS', 'Bachelor of Science in Computer Science')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')]),
        ),
    ]
