# Generated by Django 6.0.3 on 2026-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqs', '0002_alter_pyq_course_alter_pyq_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyq',
            name='year',
            field=models.IntegerField(choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015')]),
        ),
    ]
