# Generated by Django 6.0.3 on 2026-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorstudymaterial',
            name='course',
            field=models.CharField(choices=[('bsc_it', 'BSc IT'), ('bsc_cs', 'BSc CS')], default='bsc_it', max_length=20),
        ),
        migrations.AddField(
            model_name='authorstudymaterial',
            name='semester',
            field=models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('sem3', 'Semester 3'), ('sem4', 'Semester 4'), ('sem5', 'Semester 5'), ('sem6', 'Semester 6')], default='sem1', max_length=10),
        ),
    ]
