# Generated by Django 6.0.3 on 2026-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_panel', '0003_authorquiz_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorquiz',
            name='link_type',
            field=models.CharField(choices=[('material', 'Study Material')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
